# Configuration for a 'docker-compose up'. Creating a MongoDB in Docker
version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    container_name: myMongoDB
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root33
    ports:
      - "27017:27017"
