version: "3.2"

services:

  block16-01-app-cliente-viaje:
    image: block16-01-app-cliente-viaje-image
    build: ./block16-01-app-cliente-viaje
    container_name: block16-01-app-cliente-viaje-container
    ports:
      - "8081:8081"
    environment:
      - eureka.client.serviceUrl.defaultZone=http://block16-03-eureka-naming-server-container:8761/eureka/
    networks:
      - network-cloud

  block16-02-app-ticket:
    image: block16-02-app-ticket-image
    build: ./block16-02-app-ticket
    container_name: block16-02-app-ticket-container
    ports:
      - "8082:8082"
    environment:
      - restTemplate.url=http://block16-01-app-cliente-viaje-container:8081/passenger/
      - feignTrip.url=http://block16-01-app-cliente-viaje-container:8081
      - eureka.client.serviceUrl.defaultZone=http://block16-03-eureka-naming-server-container:8761/eureka/
    networks:
      - network-cloud

  block16-03-eureka-naming-server:
    image: block16-03-eureka-naming-server-image
    build: ./block16-03-eureka-naming-server
    container_name: block16-03-eureka-naming-server-container
    ports:
      - "8761:8761"
    networks:
      - network-cloud

  block16-04-gateway-api:
    image: block16-04-gateway-api-image
    build: ./block16-04-gateway-api
    container_name: block16-04-api-gateway-container
    ports:
      - "8080:8080"
    environment:
      - spring.cloud.gateway.routes[0].id=passenger
      - spring.cloud.gateway.routes[0].uri=http://block16-01-app-cliente-viaje-container:8081/
      - spring.cloud.gateway.routes[0].predicates[0]=Path=/passenger/**
      - spring.cloud.gateway.routes[1].id=trip
      - spring.cloud.gateway.routes[1].uri=http://block16-01-app-cliente-viaje-container:8081/
      - spring.cloud.gateway.routes[1].predicates[0]=Path=/trip/**
      - spring.cloud.gateway.routes[2].id=ticket
      - spring.cloud.gateway.routes[2].uri=http://block16-02-app-ticket-container:8082/
      - spring.cloud.gateway.routes[2].predicates[0]=Path=/ticket/**
      - eureka.client.serviceUrl.defaultZone= http://block16-03-eureka-naming-server-container:8761/eureka
    networks:
      - network-cloud

networks:
  network-cloud:
    driver: bridge