version: '2'
services:

    zookeeper:
        container_name: zookeeper
        image: 'wurstmeister/zookeeper'
        ports:
            - "2181:2181"
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        networks:
            - my-network

    kafka:
        container_name: my_kafka
        image: 'wurstmeister/kafka'
        depends_on:
            - zookeeper
        ports:
            - "9092:9092"

        expose:
            - "29092"

        environment:
            KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1 # localhost
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_CREATE_TOPICS: "supertopic:1:1"
#            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
#            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
#            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: '1'
#            KAFKA_MIN_INSYNC_REPLICAS: '1'
#            ALLOW_PLAINTEXT_LISTENER: yes
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
